# Generated by Django 4.2 on 2023-06-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='article_author', to='portfolio.author'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.article'),
        ),
    ]
