# Generated by Django 4.2.1 on 2023-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_area_article_blog_blogowner_comment_like_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='article', to='portfolio.author'),
        ),
    ]
